In [1]:
import numpy as np

In [2]:
a = {}
a[2] =2

In [3]:
a

{2: 2}

In [4]:
import itertools  
from collections import Counter  
ids = [1,4,3,3,4,2,3,4,5,6,1]  
c = Counter(ids)
c[1]    

2

In [5]:
a = np.array([[1,1], [2,2]])

In [6]:
a

array([[1, 1],
       [2, 2]])

In [7]:
a[[0, 1], :] = [1,2]

In [8]:
a

array([[1, 2],
       [1, 2]])

In [9]:
import tensorflow as tf

In [10]:
?tf.expand_dims

In [11]:
a = tf.constant([[1.0, 2.0],[3.0, 4.0]], name="a")

In [12]:
sess = tf.Session()

In [13]:
sess.run(a)

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [14]:
b = tf.constant([[1.0], [2.0]], name="b")

In [15]:
sess.run(a+b)

array([[2., 3.],
       [5., 6.]], dtype=float32)

In [16]:
sess.run(tf.expand_dims(tf.reduce_max(a, axis=1), 1))

array([[2.],
       [4.]], dtype=float32)

In [17]:
?tf.exp

In [18]:
c = tf.constant([[1], [2]], name="b")

In [19]:
sess.run(b*tf.to_float(c))

array([[1.],
       [4.]], dtype=float32)

In [20]:
list_a = [1,2]
list_a[-1]

2

In [23]:
list_a.pop(-2)

1

In [24]:
list_a

[2]

In [26]:
np.random.choice(1,2,False)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [27]:
list_a[[1,1]]

TypeError: list indices must be integers, not list

In [30]:
b = set([1,1])

In [31]:
a = [i for i in b]

In [32]:
a

[1]

In [33]:
6.0/13

0.46153846153846156

In [35]:
np.array((1,2,3))

array([1, 2, 3])