In [1]:
import numpy as np

In [2]:
a = {}
a[2] =2

In [3]:
a

{2: 2}

In [8]:
import itertools  
from collections import Counter  
ids = [1,4,3,3,4,2,3,4,5,6,1]  
c = Counter(ids)
c[1]    

2

In [9]:
a = np.array([[1,1], [2,2]])

In [10]:
a

array([[1, 1],
       [2, 2]])

In [11]:
a[[0, 1], :] = [1,2]

In [12]:
a

array([[1, 2],
       [1, 2]])

In [2]:
import tensorflow as tf

In [17]:
?tf.expand_dims

In [4]:
a = tf.constant([[1.0, 2.0],[3.0, 4.0]], name="a")

In [5]:
sess = tf.Session()

In [9]:
sess.run(a)

array([[ 1.,  2.],
       [ 3.,  4.]], dtype=float32)

In [13]:
b = tf.constant([[1.0], [2.0]], name="b")

In [14]:
sess.run(a+b)

array([[ 2.,  3.],
       [ 5.,  6.]], dtype=float32)

In [18]:
sess.run(tf.expand_dims(tf.reduce_max(a, axis=1), 1))

array([[ 2.],
       [ 4.]], dtype=float32)

In [19]:
?tf.exp

In [20]:
c = tf.constant([[1], [2]], name="b")

In [24]:
sess.run(b*tf.to_float(c))

ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 'Tensor("b_2:0", shape=(2, 1), dtype=int32)'