In [59]:
import numpy as np

In [60]:
a = {}
a[2] =2

In [61]:
a

{2: 2}

In [62]:
import itertools  
from collections import Counter  
ids = [1,4,3,3,4,2,3,4,5,6,1]  
c = Counter(ids)
c[1]    

2

In [63]:
a = np.array([[1,1], [2,2]])

In [64]:
a

array([[1, 1],
       [2, 2]])

In [65]:
a[[0, 1], :] = [1,2]

In [66]:
a

array([[1, 2],
       [1, 2]])

In [67]:
import tensorflow as tf

In [68]:
?tf.expand_dims

In [69]:
a = tf.constant([[1.0, 2.0],[3.0, 4.0]], name="a")

In [70]:
sess = tf.Session()

In [71]:
sess.run(a)

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [72]:
b = tf.constant([[1.0], [2.0]], name="b")

In [73]:
sess.run(a+b)

array([[2., 3.],
       [5., 6.]], dtype=float32)

In [74]:
sess.run(tf.expand_dims(tf.reduce_max(a, axis=1), 1))

array([[2.],
       [4.]], dtype=float32)

In [75]:
?tf.exp

In [76]:
c = tf.constant([[1], [2]], name="b")

In [77]:
sess.run(b*tf.to_float(c))

array([[1.],
       [4.]], dtype=float32)

In [78]:
list_a = [1,2]
list_a[-1]

2

In [79]:
list_a.pop(-2)

1

In [80]:
list_a

[2]

In [81]:
list_a[[1,1]]

TypeError: list indices must be integers, not list

In [82]:
b = set([1,1])

In [83]:
a = [i for i in b]

In [84]:
a

[1]

In [85]:
6.0/13

0.46153846153846156

In [86]:
np.array((1,2,3))

array([1, 2, 3])

In [94]:
params = tf.constant([10,20,30,40])
ids = tf.constant([[1,1,3],[2,2,2]])
print sess.run(tf.nn.embedding_lookup(params,ids))

[[20 20 40]
 [30 30 30]]


In [92]:
tf.shape(ids)

<tf.Tensor 'Shape:0' shape=(2,) dtype=int32>

In [95]:
testArray = [1,2,3]
testArray[1:5]

[2, 3]

In [100]:
testArray.extend([1,2])

In [101]:
testArray


[1, 2, 3, [1, 2], 1, 2]

In [104]:
a = np.array([1, 2, 3, 4])
b = [5, 6]
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [103]:
a

array([1, 2, 3, 4])

In [105]:
?np.concatenate

In [106]:
np.random.choice(4,2)

array([0, 3])

In [110]:
for i, j in set(zip([0,1,1], [1,2,2])):
    print i, j

0 1
1 2


In [111]:
a = [1,2,3]
b = list(a)

In [112]:
b.remove(2)

In [113]:
b

[1, 3]

In [114]:
a

[1, 2, 3]